"""
@author: Ozan
"""
H5_FILE_PATH_UNET = '.H5 File/model.h5'
LOGO = '.LOGO/univlogo.jpg'
DICE_SMOOTH = 1
LEARNING_RATE = 0.0001
PRINT =False
FEATURES_MAP=16
USE_DROPOUT = True
DROPOUT_RATE = 0.1

IMG_HEIGHT=128
IMG_WIDTH=128
IMG_CHANNELS=1
n_classes=6
REPORT = True

OUTPUT_FORMAT = '.jpg'